name: Build and deploy ASP.Net Core app to Azure Web App - backendmedisync

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: cd Backend && dotnet restore
      - name: Build
        run: cd Backend && dotnet build --configuration Release --no-restore
      - name: Test
        run: cd Backend && dotnet test --no-restore --verbosity normal || true
      - name: Publish
        run: cd Backend && dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backendmedisync-cua0dmdgh3aacrb0'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .